name: Build and Deploy LaTeX Document

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3

      - name: Build Latex PDF
        run: |
          sudo apt update
          sudo apt install latexmk texlive-full poppler-utils

          cd ./beamer/00-yolo
          latexmk -pdf ./main.tex
          mv ./main.pdf ../../gh-pages/yolo.pdf
          cd ../../

          cd ./beamer/01-optuna
          latexmk -pdf ./main.tex
          mv ./main.pdf ../../gh-pages/optuna.pdf
          cd ../../

      - name: PDF to PNG preview
        run: |
          pdftoppm -png -r 300 -f 2 -singlefile ./gh-pages/yolo.pdf ./gh-pages/yolo-preview
          pdftoppm -png -r 300 -f 2 -singlefile ./gh-pages/optuna.pdf ./gh-pages/optuna-preview

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: ./gh-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
